// Generated by purs bundle 0.14.1
var PS = {};
(function(exports) {
  "use strict";

  exports.unsafe_add_child = actor => child => () => actor.add_child(child)
  exports.unsafe_destroy = actor => () => actor.destroy()
  exports.unsafe_onButtonPressEvent = actor => cb => () =>
    actor.connect("button-press-event", (actor, event) => cb(actor)(event)())
  exports.unsafe_onButtonReleaseEvent = actor => cb => () =>
    actor.connect("button-release-event", (actor, event) => cb(actor)(event)())
})(PS["Clutter.Actor"] = PS["Clutter.Actor"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Clutter.Actor"] = $PS["Clutter.Actor"] || {};
  var exports = $PS["Clutter.Actor"];
  var $foreign = $PS["Clutter.Actor"];
  var onButtonReleaseEvent = function (dictActor) {
      return $foreign.unsafe_onButtonReleaseEvent;
  };
  var onButtonPressEvent = function (dictActor) {
      return $foreign.unsafe_onButtonPressEvent;
  };
  var destroy = function (dictActor) {
      return $foreign.unsafe_destroy;
  };
  var add_child = function (dictActor) {
      return function (dictActor1) {
          return $foreign.unsafe_add_child;
      };
  };
  exports["add_child"] = add_child;
  exports["destroy"] = destroy;
  exports["onButtonPressEvent"] = onButtonPressEvent;
  exports["onButtonReleaseEvent"] = onButtonReleaseEvent;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Control.Apply"] = $PS["Control.Apply"] || {};
  var exports = $PS["Control.Apply"];                
  var Apply = function (Functor0, apply) {
      this.Functor0 = Functor0;
      this.apply = apply;
  };                      
  var apply = function (dict) {
      return dict.apply;
  };
  exports["Apply"] = Apply;
  exports["apply"] = apply;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Control.Applicative"] = $PS["Control.Applicative"] || {};
  var exports = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];          
  var Applicative = function (Apply0, pure) {
      this.Apply0 = Apply0;
      this.pure = pure;
  };
  var pure = function (dict) {
      return dict.pure;
  };
  var liftA1 = function (dictApplicative) {
      return function (f) {
          return function (a) {
              return Control_Apply.apply(dictApplicative.Apply0())(pure(dictApplicative)(f))(a);
          };
      };
  };
  exports["Applicative"] = Applicative;
  exports["pure"] = pure;
  exports["liftA1"] = liftA1;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Control.Bind"] = $PS["Control.Bind"] || {};
  var exports = $PS["Control.Bind"];                 
  var Bind = function (Apply0, bind) {
      this.Apply0 = Apply0;
      this.bind = bind;
  };                     
  var bind = function (dict) {
      return dict.bind;
  };
  exports["Bind"] = Bind;
  exports["bind"] = bind;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Control.Monad"] = $PS["Control.Monad"] || {};
  var exports = $PS["Control.Monad"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];                
  var Monad = function (Applicative0, Bind1) {
      this.Applicative0 = Applicative0;
      this.Bind1 = Bind1;
  };
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return Control_Bind.bind(dictMonad.Bind1())(f)(function (f$prime) {
                  return Control_Bind.bind(dictMonad.Bind1())(a)(function (a$prime) {
                      return Control_Applicative.pure(dictMonad.Applicative0())(f$prime(a$prime));
                  });
              });
          };
      };
  };
  exports["Monad"] = Monad;
  exports["ap"] = ap;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Data.Function"] = $PS["Data.Function"] || {};
  var exports = $PS["Data.Function"];
  var $$const = function (a) {
      return function (v) {
          return a;
      };
  };
  exports["const"] = $$const;
})(PS);
(function(exports) {
  "use strict";

  exports.unit = {};
})(PS["Data.Unit"] = PS["Data.Unit"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Data.Unit"] = $PS["Data.Unit"] || {};
  var exports = $PS["Data.Unit"];
  var $foreign = $PS["Data.Unit"];
  exports["unit"] = $foreign.unit;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Data.Functor"] = $PS["Data.Functor"] || {};
  var exports = $PS["Data.Functor"];
  var Data_Function = $PS["Data.Function"];
  var Data_Unit = $PS["Data.Unit"];                  
  var Functor = function (map) {
      this.map = map;
  };
  var map = function (dict) {
      return dict.map;
  };
  var $$void = function (dictFunctor) {
      return map(dictFunctor)(Data_Function["const"](Data_Unit.unit));
  };
  exports["Functor"] = Functor;
  exports["void"] = $$void;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Data.Maybe"] = $PS["Data.Maybe"] || {};
  var exports = $PS["Data.Maybe"];                 
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (v) {
      return function (v1) {
          return function (v2) {
              if (v2 instanceof Nothing) {
                  return v;
              };
              if (v2 instanceof Just) {
                  return v1(v2.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe (line 230, column 1 - line 230, column 51): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
          };
      };
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["maybe"] = maybe;
})(PS);
(function(exports) {
  /* eslint-disable no-eq-null, eqeqeq */

  "use strict";

  exports["null"] = null;

  exports.notNull = function (x) {
    return x;
  };
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Data.Nullable"] = $PS["Data.Nullable"] || {};
  var exports = $PS["Data.Nullable"];
  var $foreign = $PS["Data.Nullable"];
  var Data_Maybe = $PS["Data.Maybe"];              
  var toNullable = Data_Maybe.maybe($foreign["null"])($foreign.notNull);
  exports["toNullable"] = toNullable;
})(PS);
(function(exports) {
  "use strict";

  exports.pureE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
})(PS["Effect"] = PS["Effect"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Effect"] = $PS["Effect"] || {};
  var exports = $PS["Effect"];
  var $foreign = $PS["Effect"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];
  var Control_Bind = $PS["Control.Bind"];
  var Control_Monad = $PS["Control.Monad"];
  var Data_Functor = $PS["Data.Functor"];                    
  var monadEffect = new Control_Monad.Monad(function () {
      return applicativeEffect;
  }, function () {
      return bindEffect;
  });
  var bindEffect = new Control_Bind.Bind(function () {
      return applyEffect;
  }, $foreign.bindE);
  var applyEffect = new Control_Apply.Apply(function () {
      return functorEffect;
  }, Control_Monad.ap(monadEffect));
  var applicativeEffect = new Control_Applicative.Applicative(function () {
      return applyEffect;
  }, $foreign.pureE);
  var functorEffect = new Data_Functor.Functor(Control_Applicative.liftA1(applicativeEffect));
  exports["functorEffect"] = functorEffect;
})(PS);
(function(exports) {
  "use strict";

  exports.new = function (val) {
    return function () {
      return { value: val };
    };
  };

  exports.read = function (ref) {
    return function () {
      return ref.value;
    };
  };

  exports.write = function (val) {
    return function (ref) {
      return function () {
        ref.value = val;
      };
    };
  };
})(PS["Effect.Ref"] = PS["Effect.Ref"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Effect.Ref"] = $PS["Effect.Ref"] || {};
  var exports = $PS["Effect.Ref"];
  var $foreign = $PS["Effect.Ref"];
  exports["new"] = $foreign["new"];
  exports["read"] = $foreign.read;
  exports["write"] = $foreign.write;
})(PS);
(function(exports) {
  "use strict";

  exports.getCurrentExtension = () => imports.misc.extensionUtils.getCurrentExtension()

  exports.getPath = (ext) => name => () => ext.dir.get_child(name).get_path()
})(PS["ExtensionUtils"] = PS["ExtensionUtils"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["ExtensionUtils"] = $PS["ExtensionUtils"] || {};
  var exports = $PS["ExtensionUtils"];
  var $foreign = $PS["ExtensionUtils"];
  exports["getCurrentExtension"] = $foreign.getCurrentExtension;
  exports["getPath"] = $foreign.getPath;
})(PS);
(function(exports) {
  "use strict";      
  exports.log = msg => () => log(msg)
})(PS["GJS"] = PS["GJS"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["GJS"] = $PS["GJS"] || {};
  var exports = $PS["GJS"];
  var $foreign = $PS["GJS"];
  exports["log"] = $foreign.log;
})(PS);
(function(exports) {
  "use strict";

  const DBusCallFlags = imports.gi.Gio.DBusCallFlags;

  exports.none = DBusCallFlags.NONE
})(PS["Gio.DBusCallFlags"] = PS["Gio.DBusCallFlags"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gio.DBusCallFlags"] = $PS["Gio.DBusCallFlags"] || {};
  var exports = $PS["Gio.DBusCallFlags"];
  var $foreign = $PS["Gio.DBusCallFlags"];
  exports["none"] = $foreign.none;
})(PS);
(function(exports) {
  "use strict";

  const DBus = imports.gi.Gio.DBus;
  const DBusConnection = imports.gi.Gio.DBusConnection;

  exports.session = DBus.session

  exports.call_impl = conn => bus_name => object_path => interface_name =>
    method_name => parameters => reply_type => flags => timeout_msec => cancellable => cbM => () => {
      const cb = cbM ? (_obj, res) => cbM(res)() : null;
      conn.call(bus_name, object_path, interface_name,
                method_name, parameters, reply_type, flags, timeout_msec, cancellable, cb);
    }
})(PS["Gio.DBusConnection"] = PS["Gio.DBusConnection"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gio.DBusConnection"] = $PS["Gio.DBusConnection"] || {};
  var exports = $PS["Gio.DBusConnection"];
  var $foreign = $PS["Gio.DBusConnection"];
  var Data_Nullable = $PS["Data.Nullable"];
  var call = function (conn) {
      return function (bus_name) {
          return function (object_path) {
              return function (interface_name) {
                  return function (method_name) {
                      return function (parameters) {
                          return function (reply_type) {
                              return function (flags) {
                                  return function (timeout_msec) {
                                      return function (cancellable) {
                                          return function (cb) {
                                              return $foreign.call_impl(conn)(Data_Nullable.toNullable(bus_name))(object_path)(interface_name)(method_name)(Data_Nullable.toNullable(parameters))(Data_Nullable.toNullable(reply_type))(flags)(timeout_msec)(Data_Nullable.toNullable(cancellable))(Data_Nullable.toNullable(cb));
                                          };
                                      };
                                  };
                              };
                          };
                      };
                  };
              };
          };
      };
  };
  exports["call"] = call;
  exports["session"] = $foreign.session;
})(PS);
(function(exports) {
  "use strict";

  const Gio = imports.gi.Gio;                        
  exports.new_full = schema => () => Gio.Settings.new_full(schema, null, null)
})(PS["Gio.Settings"] = PS["Gio.Settings"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gio.Settings"] = $PS["Gio.Settings"] || {};
  var exports = $PS["Gio.Settings"];
  var $foreign = $PS["Gio.Settings"];
  exports["new_full"] = $foreign.new_full;
})(PS);
(function(exports) {
  "use strict";

  const Gio = imports.gi.Gio;

  exports.new_from_directory = path => trusted => () => Gio.SettingsSchemaSource.new_from_directory(path, null, trusted)

  exports.lookup = s => name => recursive => () => s.lookup(name, recursive)
})(PS["Gio.SettingsSchemaSource"] = PS["Gio.SettingsSchemaSource"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gio.SettingsSchemaSource"] = $PS["Gio.SettingsSchemaSource"] || {};
  var exports = $PS["Gio.SettingsSchemaSource"];
  var $foreign = $PS["Gio.SettingsSchemaSource"];
  exports["new_from_directory"] = $foreign.new_from_directory;
  exports["lookup"] = $foreign.lookup;
})(PS);
(function(exports) {
  "use strict";

  const Gio = imports.gi.Gio;

  exports.new = name => () => Gio.ThemedIcon.new(name)
})(PS["Gio.ThemedIcon"] = PS["Gio.ThemedIcon"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gio.ThemedIcon"] = $PS["Gio.ThemedIcon"] || {};
  var exports = $PS["Gio.ThemedIcon"];
  var $foreign = $PS["Gio.ThemedIcon"];
  exports["new"] = $foreign["new"];
})(PS);
(function(exports) {
  "use strict"                                                 
  exports.all = imports.gi.Shell.ActionMode.ALL
})(PS["Gnome.Shell.ActionMode"] = PS["Gnome.Shell.ActionMode"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gnome.Shell.ActionMode"] = $PS["Gnome.Shell.ActionMode"] || {};
  var exports = $PS["Gnome.Shell.ActionMode"];
  var $foreign = $PS["Gnome.Shell.ActionMode"];
  exports["all"] = $foreign.all;
})(PS);
(function(exports) {
  "use strict";

  let Main;
  try { Main = imports.ui.main; } catch (_) {}

  exports.addToStatusArea = role => indicator => () => Main.panel.addToStatusArea(role, indicator)
})(PS["Gnome.UI.Main.Panel"] = PS["Gnome.UI.Main.Panel"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gnome.UI.Main.Panel"] = $PS["Gnome.UI.Main.Panel"] || {};
  var exports = $PS["Gnome.UI.Main.Panel"];
  var $foreign = $PS["Gnome.UI.Main.Panel"];
  exports["addToStatusArea"] = $foreign.addToStatusArea;
})(PS);
(function(exports) {
  "use strict";

  let Main;
  try { Main = imports.ui.main; } catch (_) {}

  exports.addKeybinding = name => settings => flags => modes => handler => () =>
    Main.wm.addKeybinding(name, settings, flags, modes, handler)
  exports.removeKeybinding = name => () => Main.wm.removeKeybinding(name)
})(PS["Gnome.UI.Main.WM"] = PS["Gnome.UI.Main.WM"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gnome.UI.Main.WM"] = $PS["Gnome.UI.Main.WM"] || {};
  var exports = $PS["Gnome.UI.Main.WM"];
  var $foreign = $PS["Gnome.UI.Main.WM"];
  exports["addKeybinding"] = $foreign.addKeybinding;
  exports["removeKeybinding"] = $foreign.removeKeybinding;
})(PS);
(function(exports) {
  "use strict";

  let PanelMenu;
  try { PanelMenu = imports.ui.panelMenu; } catch (_) {}

  exports.newButton = (alignment) => (name) => (dontCreateMenu) => () =>
    new PanelMenu.Button(alignment, name, dontCreateMenu);
})(PS["Gnome.UI.PanelMenu"] = PS["Gnome.UI.PanelMenu"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Gnome.UI.PanelMenu"] = $PS["Gnome.UI.PanelMenu"] || {};
  var exports = $PS["Gnome.UI.PanelMenu"];
  var $foreign = $PS["Gnome.UI.PanelMenu"];
  exports["newButton"] = $foreign.newButton;
})(PS);
(function(exports) {
  "use strict"                                             
  exports.ignore_autorepeat = imports.gi.Meta.KeyBindingFlags.IGNORE_AUTOREPEAT
})(PS["Meta.KeyBindingFlags"] = PS["Meta.KeyBindingFlags"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["Meta.KeyBindingFlags"] = $PS["Meta.KeyBindingFlags"] || {};
  var exports = $PS["Meta.KeyBindingFlags"];
  var $foreign = $PS["Meta.KeyBindingFlags"];
  exports["ignore_autorepeat"] = $foreign.ignore_autorepeat;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["MumbleDBus"] = $PS["MumbleDBus"] || {};
  var exports = $PS["MumbleDBus"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Gio_DBusCallFlags = $PS["Gio.DBusCallFlags"];
  var Gio_DBusConnection = $PS["Gio.DBusConnection"];                
  var StartTalking = (function () {
      function StartTalking() {

      };
      StartTalking.value = new StartTalking();
      return StartTalking;
  })();
  var StopTalking = (function () {
      function StopTalking() {

      };
      StopTalking.value = new StopTalking();
      return StopTalking;
  })();
  var methodName = function (method) {
      if (method instanceof StartTalking) {
          return "startTalking";
      };
      if (method instanceof StopTalking) {
          return "stopTalking";
      };
      throw new Error("Failed pattern match at MumbleDBus (line 13, column 21 - line 15, column 31): " + [ method.constructor.name ]);
  };
  var call = function (method) {
      return Gio_DBusConnection.call(Gio_DBusConnection.session)(new Data_Maybe.Just("net.sourceforge.mumble.mumble"))("/")("net.sourceforge.mumble.Mumble")(methodName(method))(Data_Maybe.Nothing.value)(Data_Maybe.Nothing.value)(Gio_DBusCallFlags.none)(200)(Data_Maybe.Nothing.value)(Data_Maybe.Nothing.value);
  };
  exports["StartTalking"] = StartTalking;
  exports["StopTalking"] = StopTalking;
  exports["call"] = call;
})(PS);
(function(exports) {
  "use strict";

  let St;
  try { St = imports.gi.St; } catch(_) {}

  exports.unsafe_add_style_class_name = widget => name => () => widget.add_style_class_name(name)
})(PS["St"] = PS["St"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["St"] = $PS["St"] || {};
  var exports = $PS["St"];
  var $foreign = $PS["St"];
  var add_style_class_name = function (dictWidget) {
      return $foreign.unsafe_add_style_class_name;
  };
  exports["add_style_class_name"] = add_style_class_name;
})(PS);
(function(exports) {
  "use strict";

  let St;
  try { St = imports.gi.St; } catch(_) {}

  exports.new = () => St.Icon.new()
  exports.set_gicon = icon => gicon => () => icon.set_gicon(gicon)
})(PS["St.Icon"] = PS["St.Icon"] || {});
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["St.Icon"] = $PS["St.Icon"] || {};
  var exports = $PS["St.Icon"];
  var $foreign = $PS["St.Icon"];
  exports["new"] = $foreign["new"];
  exports["set_gicon"] = $foreign.set_gicon;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.1
  "use strict";
  $PS["GnomeMumblePushToTalk"] = $PS["GnomeMumblePushToTalk"] || {};
  var exports = $PS["GnomeMumblePushToTalk"];
  var Clutter_Actor = $PS["Clutter.Actor"];
  var Data_Functor = $PS["Data.Functor"];
  var Effect = $PS["Effect"];
  var Effect_Ref = $PS["Effect.Ref"];
  var ExtensionUtils = $PS["ExtensionUtils"];
  var GJS = $PS["GJS"];
  var Gio_Settings = $PS["Gio.Settings"];
  var Gio_SettingsSchemaSource = $PS["Gio.SettingsSchemaSource"];
  var Gio_ThemedIcon = $PS["Gio.ThemedIcon"];
  var Gnome_Shell_ActionMode = $PS["Gnome.Shell.ActionMode"];
  var Gnome_UI_Main_Panel = $PS["Gnome.UI.Main.Panel"];
  var Gnome_UI_Main_WM = $PS["Gnome.UI.Main.WM"];
  var Gnome_UI_PanelMenu = $PS["Gnome.UI.PanelMenu"];
  var Meta_KeyBindingFlags = $PS["Meta.KeyBindingFlags"];
  var MumbleDBus = $PS["MumbleDBus"];
  var St = $PS["St"];
  var St_Icon = $PS["St.Icon"];                
  var log = function (msg) {
      return GJS.log("gnome-mumble-push-to-talk: " + msg);
  };
  var main = log("Welcome!");
  var init = function __do() {
      var me = ExtensionUtils.getCurrentExtension();
      var path = ExtensionUtils.getPath(me)("schemas")();
      var schemaSource = Gio_SettingsSchemaSource.new_from_directory(path)(false)();
      var schema = Gio_SettingsSchemaSource.lookup(schemaSource)("org.gnome.shell.extensions.gnome-mumble-push-to-talk")(false)();
      return Gio_Settings.new_full(schema)();
  };
  var enable = function (settings) {
      var onTalkStart = function (env) {
          return function __do() {
              log("Start talking...")();
              St_Icon.set_gicon(env.icon)(env.talkIcon)();
              return MumbleDBus.call(MumbleDBus.StartTalking.value)();
          };
      };
      var onTalkEnd = function (env) {
          return function __do() {
              log("Stop talking...")();
              St_Icon.set_gicon(env.icon)(env.muteIcon)();
              return MumbleDBus.call(MumbleDBus.StopTalking.value)();
          };
      };
      var onKeyBinding = function (env) {
          return function (stateRef) {
              return function __do() {
                  var state = Effect_Ref.read(stateRef)();
                  (function () {
                      if (state) {
                          return onTalkStart(env)();
                      };
                      return onTalkEnd(env)();
                  })();
                  Effect_Ref.write(!state)(stateRef)();
                  return false;
              };
          };
      };
      var onClick = function (cb) {
          return function (env) {
              return function (v) {
                  return function (v1) {
                      return function __do() {
                          cb(env)();
                          return true;
                      };
                  };
              };
          };
      };
      var enableTopMenu = function (env) {
          return function __do() {
              Clutter_Actor.add_child()()(env.button)(env.icon)();
              Gnome_UI_Main_Panel.addToStatusArea("mumble")(env.button)();
              Data_Functor["void"](Effect.functorEffect)(Clutter_Actor.onButtonPressEvent()(env.button)(onClick(onTalkStart)(env)))();
              return Data_Functor["void"](Effect.functorEffect)(Clutter_Actor.onButtonReleaseEvent()(env.button)(onClick(onTalkEnd)(env)))();
          };
      };
      var enableShortCut = function (env) {
          return function __do() {
              var stateRef = Effect_Ref["new"](false)();
              return Data_Functor["void"](Effect.functorEffect)(Gnome_UI_Main_WM.addKeybinding("toggle-mumble")(settings)(Meta_KeyBindingFlags.ignore_autorepeat)(Gnome_Shell_ActionMode.all)(onKeyBinding(env)(stateRef)))();
          };
      };
      var createEnv = function __do() {
          var button = Gnome_UI_PanelMenu.newButton(0.0)("Mumble")(false)();
          var muteIcon = Gio_ThemedIcon["new"]("face-shutmouth-symbolic")();
          var talkIcon = Gio_ThemedIcon["new"]("face-smile-big-symbolic")();
          var icon = St_Icon["new"]();
          St.add_style_class_name()(icon)("system-status-icon")();
          St_Icon.set_gicon(icon)(muteIcon)();
          return {
              button: button,
              icon: icon,
              muteIcon: muteIcon,
              talkIcon: talkIcon
          };
      };
      return function __do() {
          log("enable called")();
          var env = createEnv();
          enableTopMenu(env)();
          enableShortCut(env)();
          return env;
      };
  };
  var disable = function (env) {
      var disableTopMenu = Clutter_Actor.destroy()(env.button);
      var disableShortCut = Gnome_UI_Main_WM.removeKeybinding("toggle-mumble");
      return function __do() {
          log("disable called")();
          disableTopMenu();
          return disableShortCut();
      };
  };
  var extension = {
      enable: enable,
      disable: disable,
      init: init
  };
  exports["init"] = init;
  exports["enable"] = enable;
  exports["disable"] = disable;
  exports["extension"] = extension;
  exports["log"] = log;
  exports["main"] = main;
})(PS);
PS["GnomeMumblePushToTalk"].main();
// necessary footer to transform a spago build into a valid gnome extension
let GnomeMumblePushToTalkEnv = null;
let GnomeMumblePushToTalkSettings = null;
function init() { GnomeMumblePushToTalkSettings = PS["GnomeMumblePushToTalk"]["extension"].init(); }
function enable() { GnomeMumblePushToTalkEnv = PS["GnomeMumblePushToTalk"]["extension"].enable(GnomeMumblePushToTalkSettings)(); }
function disable() { PS["GnomeMumblePushToTalk"]["extension"].disable(GnomeMumblePushToTalkEnv)(); }
